### ISSUE TITLE
Building Error in Windows

### ISSUE THREAD

**Issue by mes9** [JuliaStats/GLMNet.jl#13]
When I try to build the GLMNet.jl it tells me that the file is not found. I dug around and it looks like the problem is inside the build.jl file:

``` javascript
pic = @windows ? "" : "-fPIC"
run(`gfortran -m$WORD_SIZE -fdefault-real-8 -ffixed-form $pic -shared -O3 glmnet5.f90 -o libglmnet.so`)
```

and when the `run( )` line is read, under windows it will change `$pic` to `''` instead of an actual blank, which messes up the build. When I removed the `$pic` from that line, it built fine

**Comment by simonbyrne** [comment]
Supposedly mingw is available on appveyor, perhaps it is worth enabling it?

**Comment by mogit** [comment]
Hey. I was trying to build GLMNet for Julia on Windows and I get following errors .

![julia](https://user-images.githubusercontent.com/1769704/30764289-dbabc414-a007-11e7-9b2b-a1a38792f378.PNG)

**Comment by amellnik** [comment]
@mogit You can install `gfortran` via Msys2 by following the instructions here: https://github.com/orlp/dev-on-windows/wiki/Installing-GCC--&-MSYS2

**Comment by raphaelsaavedra** [comment]
Hello,

I'm facing the exact same problem as @mogit. I have tried @amellnik's solution but it hasn't produced any change in the error.

**Comment by amellnik** [comment]
@raphaelsaavedra Did you also add the location of `gfortran.exe` to your path?  It's something like `C:\msys64\mingw64\bin`.

**Comment by raphaelsaavedra** [comment]
Hey @amellnik, thanks for the quick answer. Yes, I have added the location of both mingw64 and 32 to my path. 

When trying to run gfortran on MinGW, the following error occurs:

![image](https://user-images.githubusercontent.com/29098169/36799484-10aa3cda-1c8c-11e8-82c6-a804723dc1f9.png)

I have followed all instructions in the link you provided before. I'll also add I'm working on Windows 7. My friend who has a mac had no issues.

**Comment by amellnik** [comment]
That's expected.  You should see the same thing if you run it from powershell/cmd in windows if you also added it to the windows (not Msys2) path.  If that's the case then you should be able to run julia and try to add `GLMNet` again.

**Comment by raphaelsaavedra** [comment]
@amellnik I managed to make it work by running Julia as administrator. Apparently my user did not have the necessary permissions to run gfortran while building GLMNet? Either way thank you for the help.

**Comment by Jacob-Stevens-Haas** [comment]
@amellnik Thanks! I had the same problem, and the same solution.

**Comment by RuilinOuyang** [comment]
Hello @amellnik,
I'm also having the same problem as  @mogit, but I'm using a Mac. Is there any suggestions? Thank you!

**Comment by amellnik** [comment]
Hi @RuilinOuyang -- as it happens I just became a Mac user myself.  You can install `gfortran` via Homebrew with `brew install gcc` and everything should work fine after that.

**Comment by RuilinOuyang** [comment]
@amellnik  Thank you! I did what you said, it's working now.

**Comment by PaulSoderlind** [comment]
Distributing compiled dependencies would be a great help to users.
