### ISSUE TITLE
how to specify family

### ISSUE THREAD

**Issue by aw2018** [JuliaStats/GLMNet.jl#34]
How to specify the family like R programming glmnetcv(X, y,family = "binomial")?

**Comment by JackDunnNZ** [comment]
You can use `path = glmnetcv(X, y, Binomial())`

There is an example in the tests here: https://github.com/JuliaStats/GLMNet.jl/blob/f1e253507dfae6538075cbd8c054ff9b5fdfbc22/test/runtests.jl#L258
