### ISSUE TITLE
Multivariate normal L1 regression

### ISSUE THREAD

**Issue by BenjaminDoran** [JuliaStats/GLMNet.jl#65]
Maybe i'm blind, but how can I fit a linear lasso model on multiple dependent variables? 

There doesn't seem to be a method for 

```
X = rand(100, 10)
Y = rand(100, 4)
path = glmnet(X, Y,  Normal())
# or 
path = glmnet(X, Y,  MvNormal())
```

**Comment by orenbenkiki** [comment]
Any chance this PR would be merged? My problem requires a multi-response Lasso. GLMNet seems to be my only option but w/o this PR I can't access this functionality from my Julia code... Please?

**Comment by BenjaminDoran** [comment]
I would obviously also like my PR to be merged, but this repo doesn't seem to be actively maintained right now. 

@JackDunnNZ was the last commit on the repo, so maybe he knows who to talk to about getting PRs merged. I am happy to make updates to my PR to help it get merged.

If you need my patch right now, you can install locally from my fork: https://github.com/BenjaminDoran/GLMNet.jl/tree/master

in your project's julia [environment](https://pkgdocs.julialang.org/v1/environments/) 

you can add packages directly from git

```
using Pkg; Pkg.add("https://github.com/BenjaminDoran/GLMNet.jl")
``` 
or from the REPL

```
julia>]
pkg>add https://github.com/BenjaminDoran/GLMNet.jl
```

Note that when updating the julia environment, julia may get confused and use the registered version rather than the fork. This should hopefully be resolved by the inclusion of `[source]` tags in the environment's `Project.toml` file. But that feature is slated to come in version Julia 1.11. In the meantime removing the package, and reinstalling like above fixes the issue.

**Comment by JackDunnNZ** [comment]
Thanks for the ping @BenjaminDoran , I merged and tagged a release

**Comment by orenbenkiki** [comment]
Wow! Many thanks for the quick responses!
