### ISSUE TITLE
Allow for sparse predictor matrix

### ISSUE THREAD

**Issue by lendle** [JuliaStats/GLMNet.jl#9]
The fortran code has methods for CSR predictor matrixes.  Currently julia only supports sparse matrixes in CSC format in Base, right? How difficult would it be to use glmnet's sparse capabilities?

(I might take a crack at this at some point but I figured I'd open an issue to see if someone else wants to work on it too.)

**Comment by simonster** [comment]
CSR is just transposed CSC so you could probably just give it that. It would also be pretty trivial to add sparse support to Lasso.jl.

**Comment by simonster** [comment]
I haven't benchmarked it at all, but Lasso.jl master now supports sparse matrices.

**Comment by jeffwong** [comment]
+1 on making glmnet able to operate on sparse matrices. As far as I can see, Lasso.jl does not support penalty.factor.

@simonster I have a sparse model matrix that came from

```
X = ModelMatrix{SparseMatrixCSC{Float64, Integer}}(ModelFrame(@formula(y ~ x), df)).m
```

How should I pass this to the fortran code?

**Comment by JackDunnNZ** [comment]
As I understand it, this was added in #25
